Repository core-ds/core-components, pull requests merged in 2022-09, with the labels that each got.

#249 fix(radio-group): added onBlur and onFocus
  packages/radio-group/src/Component.tsx
Labels: approved

#248 fix(select): removed ssr warning
  package.json
  packages/select/package.json
  packages/select/src/components/base-select/Component.tsx
  yarn.lock
Labels: approved

#246 fix(button): increased click area of the active state
  packages/button/src/__image_snapshots__/hover-button-screenshots-pressed-state-view-0-colors-1-snap.png
  packages/button/src/__image_snapshots__/hover-button-screenshots-pressed-state-view-1-colors-1-snap.png
  packages/button/src/__image_snapshots__/hover-button-screenshots-pressed-state-view-2-colors-0-snap.png
  packages/button/src/__image_snapshots__/hover-button-screenshots-pressed-state-view-2-colors-1-snap.png
  packages/button/src/index.module.css
  packages/themes/src/mixins/button/click.css
  packages/themes/src/mixins/button/corp.css
  packages/themes/src/mixins/button/intranet.css
  packages/themes/src/mixins/button/mobile.css
  packages/themes/src/mixins/button/site.css
Labels: approved

#245 fix(base-modal): Added element matches polyfill for IE11
  package.json
  packages/base-modal/package.json
  packages/base-modal/src/Component.tsx
  yarn.lock
Labels: approved

#94 fix(intl-phone-input): fixed on ios 14 and lowest
  packages/intl-phone-input/src/component.tsx
Labels: approved

#95 fix(gallery): fixed height of swiper on ios 14 and lowest
  packages/gallery/src/components/image-viewer/component.tsx
  packages/gallery/src/index.module.css
Labels: approved

#198 fix: renamed default classnames
  packages/pure-cell/src/component.tsx
  packages/pure-cell/src/components/addon/index.module.css
  packages/pure-cell/src/docs/description.mdx
  packages/pure-cell/src/index.module.css
  packages/spinner/src/Component.tsx
  packages/spinner/src/__snapshots__/Component.test.tsx.snap
  packages/spinner/src/default.module.css
  packages/spinner/src/index.module.css
  packages/spinner/src/inverted.module.css
  packages/utils/test-utils.ts
Labels: approved

#223 fix(input-autocomplete): add props custom input
  packages/input-autocomplete/src/Component.mobile.tsx
  packages/input-autocomplete/src/docs/description.mdx
Labels: approved

#240 fix(pure-cell): fix pure-cell text
  packages/pure-cell/src/components/text/component.tsx
Labels: approved

#243 feat(toast-plate): added inverted views
  packages/notification-manager/src/__snapshots__/component.test.tsx.snap
  packages/notification/src/__snapshots__/Component.test.tsx.snap
  packages/notification/src/docs/Component.stories.mdx
  packages/themes/src/dark.css
  packages/toast-plate/src/__image_snapshots__/click-toast-plate-action-button-2-snap.png
  packages/toast-plate/src/__image_snapshots__/click-toast-plate-inverted-views-2-snap.png
  packages/toast-plate/src/__image_snapshots__/default-toast-plate-action-button-snap.png
  packages/toast-plate/src/__image_snapshots__/default-toast-plate-inverted-views-snap.png
  packages/toast-plate/src/__snapshots__/component.test.tsx.snap
  packages/toast-plate/src/component.screenshots.test.tsx
  packages/toast-plate/src/component.tsx
  packages/toast-plate/src/default.module.css
  packages/toast-plate/src/docs/Component.stories.mdx
  packages/toast-plate/src/index.module.css
  packages/toast-plate/src/inverted.module.css
  packages/toast-plate/src/vars.css
  packages/toast/src/__snapshots__/component.test.tsx.snap
  packages/toast/src/docs/component.stories.mdx
Labels: approved

#192 feat(vars): introducing vars bundles
  packages/vars/src/bundle/site.css
Labels: draft

#241 feat(confirmation-v1): return old confirmation
  docs/16.confirmation-update.stories.mdx
  packages/confirmation-v-1/CHANGELOG.md
  packages/confirmation-v-1/package.json
  packages/confirmation-v-1/src/Component.test.tsx
  packages/confirmation-v-1/src/__image_snapshots__/confirmation-v-1-code-char-amount-align-sprite-snap.png
  packages/confirmation-v-1/src/__image_snapshots__/confirmation-v-1-code-checking-code-sending-sprite-snap.png
  packages/confirmation-v-1/src/__image_snapshots__/confirmation-v-1-interactions-tests-open-don-t-receive-sms-snap.png
  packages/confirmation-v-1/src/__image_snapshots__/confirmation-v-1-no-attempts-left-message-sprite-snap.png
  packages/confirmation-v-1/src/__image_snapshots__/confirmation-v-1-phone-phone-mask-countdown-sprite-snap.png
  packages/confirmation-v-1/src/__image_snapshots__/confirmation-v-1-sign-error-sprite-snap.png
  packages/confirmation-v-1/src/__snapshots__/Component.test.tsx.snap
  packages/confirmation-v-1/src/component.screenshots.test.tsx
  packages/confirmation-v-1/src/component.tsx
  packages/confirmation-v-1/src/components/code-input/component.tsx
  packages/confirmation-v-1/src/components/code-input/index.module.css
  packages/confirmation-v-1/src/components/code-input/index.ts
  packages/confirmation-v-1/src/components/code-input/utils.test.ts
  packages/confirmation-v-1/src/components/code-input/utils.ts
  packages/confirmation-v-1/src/components/countdown-loader/component.tsx
  packages/confirmation-v-1/src/components/countdown-loader/index.module.css
  packages/confirmation-v-1/src/components/countdown-loader/index.ts
  packages/confirmation-v-1/src/components/countdown/component.tsx
  packages/confirmation-v-1/src/components/countdown/index.module.css
  packages/confirmation-v-1/src/components/countdown/index.ts
  packages/confirmation-v-1/src/components/index.ts
  packages/confirmation-v-1/src/components/overlimit/component.tsx
  packages/confirmation-v-1/src/components/overlimit/index.module.css
  packages/confirmation-v-1/src/components/overlimit/index.ts
  packages/confirmation-v-1/src/components/sign-confirmation/component.tsx
  packages/confirmation-v-1/src/components/sign-confirmation/index.module.css
  packages/confirmation-v-1/src/components/sign-confirmation/index.ts
  packages/confirmation-v-1/src/docs/Component.stories.mdx
  packages/confirmation-v-1/src/docs/description.mdx
  packages/confirmation-v-1/src/index.module.css
  packages/confirmation-v-1/src/index.ts
  packages/confirmation-v-1/src/vars.css
  packages/confirmation-v-1/tsconfig.json
Labels: approved

#224 fix(base-modal): Скролл вверх модалки
  package.json
  packages/action-button/src/Component.screenshots.test.tsx
  packages/action-button/src/hooks.ts
  packages/base-modal/package.json
  packages/base-modal/src/Component.tsx
  packages/bottom-sheet/src/__snapshots__/component.test.tsx.snap
  packages/drawer/src/__snapshots__/Component.test.tsx.snap
  packages/input-autocomplete/src/__snapshots__/Component.test.tsx.snap
  yarn.lock
Labels: approved

#230 feat(code-input): update mobile version
  packages/code-input/src/component.tsx
  packages/code-input/src/components/input/index.module.css
  packages/confirmation/src/__image_snapshots__/confirmation-code-char-amount-align-sprite-snap.png
Labels: approved

#182 feat(pure-cell): removed isMultiline prop
  .changeset/healthy-cobras-admire.md
  packages/pure-cell/src/component.test.tsx
  packages/pure-cell/src/components/text/component.tsx
  packages/pure-cell/src/components/text/index.module.css
  packages/pure-cell/src/docs/description.mdx
Labels: approved, breaking change

#269 feat(themes): remove click theme
  .changeset/purple-seals-draw.md
  packages/themes/src/mixins/click.css
  packages/themes/src/mixins/code-input/click.css
Labels: approved

#195 feat: add usages
  .storybook/blocks/component-header/ComponentHeader.module.css
  .storybook/blocks/component-header/ComponentHeader.tsx
  .storybook/blocks/status/Status.module.css
  .storybook/usages.json
  package.json
  tools/update-usages.js
  tsconfig.storybook.json
Labels: draft
